#!/bin/bash
nvcc -o main main.cu tools.cpp kernel.cu order_3.cu order_4.cu order_5.cu order_6.cu order_7.cu order_8.cu order_9.cu order_10.cu -lcublas -gencode arch=compute_86,code=sm_86 

./main ./Data/ ./Data/ 32 3 32 50 0.01 0.01